### ISSUE TITLE
NotDownloading

### ISSUE THREAD

**Issue by DianoteHD** [angturil/SongRequestManager#21]
I tried to get the RequestManager working.
The bot is in the chat. the commands ar working but the songs in the queue are not downloading.
When i press play the disappear and going to history.

I don't know where the problem is.
I hope someone can help me.

Dianote

**Comment by angturil** [comment]
Issues were with Beatsaver.com itself. 
  
   ---------- Original Message ----------
   From: DianoteHD <notifications@github.com>
   Date: January 2, 2020 at 4:08 PM
   
   
   I tried to get the RequestManager working. The bot is in the chat. the commands ar working but the songs in the queue are not downloading. When i press play the disappear and going to history.
   I don't know where the problem is. I hope someone can help me.
   Dianote

**Comment by DianoteHD** [comment]
Now it works.
Thank you :D
